import type { Metadata } from "next";
import "./globals.css";
import LenisProvider from '@/components/providers/LenisProvider'
import LayoutWrapper from './LayoutWrapper';

export const metadata: Metadata = {
  title:  "ROBOTICS CLUB SRMCEM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased overflow-x-hidden bg-bg-main"
      >
        <LenisProvider>
          <LayoutWrapper>
            {children}
          </LayoutWrapper>
        </LenisProvider>
      </body>
    </html>
  );
}
