import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from '@/modules/layout/nav'
import Footer from '@/modules/layout/footer'
import LenisProvider from '@/components/providers/LenisProvider'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}
      >
        <LenisProvider>
          <div className="absolute top-0 w-full h-28 bg-transparent flex items-center justify-between px-12 z-[999]">
            <Nav />
          </div>
          {children}
          <Footer/>
        </LenisProvider>
      </body>
    </html>
  );
}
